services:
  app:
    build:
      dockerfile: './Dockerfile'
    volumes:
      - './:/app'
    command: >
      /bin/sh -c 'python /app/main.py'
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - network
  database:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - '.env'
    networks:
      - network
networks:
  network:
